
spring:
  application:
    name: application.name
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://${MEDIFE_DATABASE_HOST:localhost}:$MEDIFE_DATABASE_PORT:5432}/${MEDIFE_DATABASE_SCHEMA:mydatabase}
    username: ${MEDIFE_DATABASE_USERNAME:myuser}
    password: ${MEDIFE_DATABASE_PASSWORD:postgresql}
  jpa:
    database-platform: org.hibernate.dialect.secret
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER_URL:http://localhost:8080/realms/camdoctor}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8085

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

jwt:
  auth:
    converter:
      resource-id: subscriber-client
      principal-attribute: principal_username

medife:
  log:
    aggregator: ${LOG_AGGREGATOR:http://localhost:3100/loki/api/v1/push}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: subscriber
  tracing:
    sampling:
      probability: 1.0

jitsi:
  appId: ${JITSI_APPID}
  appSecret: ${JITSI_APPSECRET}