logging:
  level:
    root: INFO
server:
  port: 8080
spring:
  datasource:
    initialSize: 0
    initialize: false
    minEvictableIdleTimeMillis: 5000
    minIdle: 0
    password: root
    timeBetweenEvictionRunsMillis: 5000
    url: jdbc:postgresql://localhost:5432/schema
    username: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  sql:
    init:
      continue-on-error: true
  flyway:
    enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    supportedSubmitMethods: ''
    try-it-out-enabled: false
